### ISSUE TITLE
Installation error on Manjaro Linux (shell script?)

### ISSUE THREAD

**Issue by WolframStrauss** [omnetpp/opp_env#19]
Hi,
I am about to install `opp_env` on [manjaro-kde-23.1.3-240113-linux66.iso](https://manjaro.org/download/). The issue in the **Important** note: `error: externally-managed-environment`, I tried to solve with the Python `venv` solution. The installation works fine. In the active `venv` environment, starting `opp_env` leads to the following error:
```terminal
Traceback (most recent call last):
  File "/home/str/projects/omnetpp-inet/bin/opp_env", line 5, in <module>
    from opp_env.opp_env import main
  File "/home/str/projects/omnetpp-inet/lib/python3.11/site-packages/opp_env/opp_env.py", line 14, in <module>
    from packaging.version import Version
ModuleNotFoundError: No module named 'packaging'
```
There is a `~/.local/bin` entry in the `PATH` environment variable, but no such path. Section [Installing opp_env on Linux and macOS](https://github.com/omnetpp/opp_env?tab=readme-ov-file#installing-opp_env-on-linux-and-macos) in the [README](https://github.com/omnetpp/opp_env?tab=readme-ov-file#opp_env-automated-installation-of-omnet-simulation-frameworks) is referring to
> When you install `opp_env` using pip, it installs the `opp_env` Python module, as well as a small script into your system's path (e.g. `~/.local/bin`) that allows you to invoke it from the shell.

Which script is it?

Thank you, kind regards. Wolfram

**Comment by rhornig** [comment]
If you install opp_env into a virtual environment the the script itself will be installed to the virtual env directory's `bin` directory. `.local/bin` is used only of you use the system python install. (the name of the script is also `opp_env`

**Comment by rhornig** [comment]
as for the error, you may need to install the packaging module. i.e. `pip install packaging`. I was sort of assuming that the packagig module is installed, but indeed, on a clear machine, this must be also installed. Thanks for the report.

**Comment by rhornig** [comment]
Thanks. I have added the missingpackage to the requirements so you no longer have to install it manually. Also modified the README file and removed the --user option as cirtual environments are the preferred was to use python.
