### ISSUE TITLE
INET build does not work in debug mode

### ISSUE THREAD

**Issue by Kamysek** [omnetpp/opp_env#2]
Hello,

I hope this message finds you well. I wanted to report an issue I encountered while trying to install and build INET in Debug using the opp_env installation for OMNeT++ 6.0.x and NET 4.5.0 on my M1 MacBook.

Firstly, I would like to mention that the installation process went smoothly, without any apparent issues. All the necessary components were successfully installed, indicating that the installation itself is functioning correctly.

However, when attempting to build the INET project in a Debug version, I encountered an error. It is important to note that building the project in a Release version does not produce any errors and functions as expected.

The error in the build looks the following:

```
Creating shared library: ../out/clang-debug/src/libINET_dbg.dylib
ld: warning: directory not found for option '-L/Users/josefkamysek/Documents/Coding/Gradys/opp_env_install/omnetpp-6.0.x/tools/macos.aarch64/lib'
ld: warning: directory not found for option '-F/Users/josefkamysek/Documents/Coding/Gradys/opp_env_install/omnetpp-6.0.x/tools/macos.aarch64/lib'
ld: library not found for -loppenvir_dbg
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile:1849: ../out/clang-debug/src/libINET_dbg.dylib] Error 1
make[1]: Leaving directory '/Users/josefkamysek/Documents/Coding/Gradys/opp_env_install/inet-4.5.0/src'
make: *** [Makefile:7: all] Error 2
"make MODE=debug -j7 all" terminated with exit code 2. Build might be incomplete.

```

If you need additional information please let me know :) 

Greetings,
Josef

**Comment by rhornig** [comment]
We welcome you as the first external user of our new tool. Please test and report issues...

By default only release mode is used during installation (to save time for users). You probably installed OMNeT++ (by default in release). Later, when you try to install INET in debug mode, the build system will not recognize that OMNeT++ was only build in release mode and will not trigger a debug build from OMNeT++.

As a workaround, delete both INET and OMNeT++ (6.0.1) and reinstall inet (with --mode=release,debug). That will build both debug and release from OMNeT++ and you will not have the above problem.

We will fix this later by storing for each project what mode was used at last build and trigger the necessary build command for OMNeT++.

**Comment by Kamysek** [comment]
Thank you very much for your fast response. I will try to install omnetpp and inet the way you described. Do you by any chance have additional knowledge on how to run the omnetpp samples with the 3d open street maps on a M1? Packages such as osgEarth are not supported also for newer Linux versions it does not come with an automated installation :)

**Comment by Kamysek** [comment]
The installation in debug and release mode now works :)

**Comment by rhornig** [comment]
At the moment I'm concentrating on the base OMNeT++ functionality, so 3D rendering is disabled on all builds. OpenSceneGraph has it's own NIX package, so that would not be a problem, but it seems that osgEarth is pretty much abandoned and nobody took the time to create a package for it in NIX (and the dropping from debian is also telling...).

In retrospect, osgEarth seems to be a dead end and we plan to deprecate it :( Maybe integration with Universal Scene Description would be the next logical step replacing it.
