### ISSUE TITLE
opp_env as a dependency in other Nix environments

### ISSUE THREAD

**Issue by lumpiluk** [omnetpp/opp_env#9]
I'm working on a project where OMNeT++ and Veins are part of a larger set of dependencies, and I have been thinking about including a shell.nix. Is there a straight-forward or recommended way to include opp_env or its outputs in an existing shell.nix, for example?

> If you have any issues or questions, feel free to open an issue on the GitHub repository.

This may be more of a question than an issue. I just started getting into Nix, so apologies if the answer is obvious

**Comment by rhornig** [comment]
At the moment, we don't have a mechanism to create a proper nix package from the models using opp_env. We do have all the information, so in theory it would be possible to create a proper nix file in a future version. On long term it would be great to have proper nix flake files for all models. Right now, when you open an opp_env shell, we generate a flake file in the `.opp_env_workspace` directory that provide `devShells` i.e. defines all the required dependencies of the modell, but it does not provide build instructions.

I will create a separate feature request just to keep this use-case around for the future.
